version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bnpl_postgres
    environment:
      POSTGRES_DB: bnpl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bnpl_network

  app:
    build: .
    container_name: bnpl_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bnpl_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - bnpl_network

volumes:
  postgres_data:

networks:
  bnpl_network:
